name = "longrange"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "cargo install wasm-bindgen-cli && cargo build --release --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/release/longrange.wasm --out-dir dist --target web --no-typescript && cp index.html dist/"
