name = "longrange"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[rules]]
type = "Data"
globs = ["**/*.wasm"]
fallthrough = false

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false
